### PR TITLE
Added a way to control ordering (inserting numbers) into a channel

### PR DESCRIPTION
**Pull request by idcrook**
Included updating the built-in tests

### CODE REVIEW

**Comment by petervizi** [comment]
Hey dpcrook,

Two minor comments:
1. Could you please describe a use case for this new parameter?
2. I would prefer this new optional parameter to be the last one, that way it won't brake existing code:

```
def __init__(self, id_, value, tags=list(), minValue=None, maxValue=None, unit=None, at=None, datapoints=None, id_name=None):
```

Thanks,
Peter

**Comment by idcrook** [comment]
Hello Peter.

Thanks for sharing your excellent eeml library for python.

As a use case: I have used it so I can enumerate the channel names,
and include strings in their names.  This is helpful to provide a more
descriptive name along with keeping a sortable order.

And example using the code  can be found here:

   https://xively.com/feeds/123164

where you may note that the first four fields are uploaded with a
number and named field, and appear 0,1,2,3 (screenshot attached)...

[image: Inline image 2]

On your second comment, I have no reason on why it could not be placed
at the end of the named arg list... I had not really consider the case
of unnamed arguments, but instead was thinking of putting it next to
the closely related argument.  I was trying to have as little impact
to the existing API as possible, as well as preserve backwards
compatibility.  Putting it at the end of the arg list would do an even
better job of that.

Thanks, David

**Comment by idcrook** [comment]
Hello Peter.

Thanks for sharing your excellent eeml library for python.  Doing an email reply seems to have biffed the formatting.

As a use case: I have used it so I can enumerate the channel names,
and also include descriptive strings in their names.  This is helpful to provide a more
descriptive name along with keeping a sortable order.

And example using the code  can be found here:

   https://xively.com/feeds/123164 

where you may note that the first four fields are uploaded with a
number and named field, and appear 0,1,2,3 ...

image

On your second comment, I have no reason on why it could not be placed
at the end of the named arg list... I had not really consider the case
of unnamed arguments, but instead was thinking of putting it next to
the closely related argument.  I was trying to have as little impact
to the existing API as possible, as well as preserve backwards
compatibility.  Putting it at the end of the arg list would do an even
better job of that.  

Did you want me to make that edit, and then re-request a pull?

Thanks, David

**Comment by idcrook** [comment]
Closing this old pull request

**Pull request closed without merging**
